/*

MIT License

Copyright(c) 2018 — 2019 Yogensia

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files(the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/

'use strict';

/**
 * Generate Webview header HTML.
 * @param isKnownWord Whether this is function or hook in this extension dictionary.
 * @param searchString Full search URL generated by extension. Can be a google search or a WPDocs link.
 * @param searchTerm Word that the user is searching for.
 * @param cssTheme Link HTML tag for the theme to use in webview.
 * @param WPLogoRes vscode-resource URL for the header WordPress logo.
 */
export function getHtmlHead(isKnownWord = false, searchString = "", searchTerm = "", cssTheme = "", WPLogoRes = "") {
  var output = `<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head profile="http://gmpg.org/xfn/11">
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>WordPress Developer Resources</title>
  <link rel='stylesheet' id='wp-dev-sass-compiled-css' href='https://developer.wordpress.org/wp-content/themes/pub/wporg-developer/stylesheets/main.css?ver=20190603' type='text/css' media='all' />
  <link rel='stylesheet' id='dashicons-css' href='https://developer.wordpress.org/wp-includes/css/dashicons.min.css?ver=5.3-alpha-45546' type='text/css' media='all' />
  ` + cssTheme + `
</head>
<body id="wordpress-org" class="wp-parser-function-template-default single single-wp-parser-function postid-0 no-customize-support">
<div id="page" class="hfeed site devhub-wrap">
<main id="main" class="site-main" role="main">
<span id="top"></span>
<header id="main-header">
<h1>
  <a href="https://wordpress.org"><img alt="WordPress" src="` + WPLogoRes + `" /></a>
</h1>
<nav aria-label="Main Menu">
  <ul id="wporg-header-menu" class=" nav-menu">
    <li class="menu-item"><a href="https://wordpress.org/showcase/" data-title="See some of the sites built on WordPress.">Showcase</a></li>
    <li class="menu-item"><a href="https://wordpress.org/themes/" data-title="Find just the right look for your website.">Themes</a></li>
    <li class="menu-item"><a href="https://wordpress.org/plugins/" data-title="Plugins can extend WordPress to do almost anything you can imagine.">Plugins</a></li>
    <li class="menu-item"><a href="https://wordpress.org/mobile/" data-title="Take your website on the go!">Mobile</a></li>
    <li class="menu-item"><a href="https://wordpress.org/support/" data-title="Forums, documentation, help.">Support</a></li>
    <li class="menu-item"><a href="https://make.wordpress.org/" data-title="Contribute your knowledge.">Get Involved</a></li>
    <li class="menu-item"><a href="https://wordpress.org/about/" data-title="About the WordPress Organization, and where we're going.">About</a></li>
    <li class="menu-item"><a href="https://wordpress.org/news/" data-title="Come here for the latest scoop.">Blog</a></li>
    <li class="menu-item"><a href="https://wordpress.org/hosting/" data-title="Find a home for your blog.">Hosting</a></li>
  </ul>
</nav>
</header>
`;

  // Add a link to pages for know words, or a link to the google search for unknown words.
  if (isKnownWord) {
    output += '<p id="swpd-intro">This article is part of the <a href="https://developer.wordpress.org/reference/">WordPress.org Code Reference</a>. You can also <a class="page-link" href="' + searchString + '">open this article in your browser</a>.</p>';
  } else {
    output += '<p id="swpd-intro">Sorry, the term you searched for isn\'t recognized by the SearchWordPressDocs extension. You are seeing Google\'s first result for your search. If you prefer, you can <a class="page-link" href="https://google.com/search?q=site:developer.wordpress.org ' + searchTerm + '">open Google\'s search results in your browser.</a></p>';
  }

  return output;
}

/**
 * Generate footer for the webview, and add closing tags.
 */
export function getHtmlFooter() {
  return `</div>
</section>
</div>
</article>
</main>
</div>
</main>
</div>
</body>
</html>`;
}