/*

MIT License

Copyright(c) 2018 — 2019 Yogensia

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files(the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/

'use strict';

/**
 * Generate Webview header HTML.
 * @param isKnownWord bool  Whether this is function or hook in this extension dictionary.
 * @param searchString string  Full search URL generated by extension. Can be a google search or a WPDocs link.
 * @param searchTerm string  Word that the user is searching for.
 */
export function getHtmlHead(isKnownWord = false, searchString = "", searchTerm = "", cssTheme = "") {
  var output = `<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head profile="http://gmpg.org/xfn/11">
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>WordPress Developer Resources</title>
<link rel='stylesheet' id='wp-dev-sass-compiled-css' href='https://developer.wordpress.org/wp-content/themes/pub/wporg-developer/stylesheets/main.css?ver=20190603' type='text/css' media='all' />
<link rel='stylesheet' id='dashicons-css' href='https://developer.wordpress.org/wp-includes/css/dashicons.min.css?ver=5.3-alpha-45546' type='text/css' media='all' />
` + cssTheme + `
</head>
<body id="wordpress-org" class="wp-parser-function-template-default single single-wp-parser-function postid-0 no-customize-support">
<div id="page" class="hfeed site devhub-wrap">
<main id="main" class="site-main" role="main">
<span id="top"></span>`;

  // Add a link to pages for know words, or a link to the google search for unknown words.
  if (isKnownWord) {
    output += '<p id="swpd-intro">This article is part of the <a href="https://developer.wordpress.org/reference/">WordPress.org Code Reference</a>. You can also <a class="page-link" href="' + searchString + '">open this article in your browser</a>.</p>';
  } else {
    output += '<p id="swpd-intro">Sorry, the term you searched for isn\'t recognized by the SearchWordPressDocs extension. You are seeing Google\'s first result for your search. If you prefer, you can <a class="page-link" href="https://google.com/search?q=site:developer.wordpress.org ' + searchTerm + '">open Google\'s search results in your browser.</a></p>';
  }

  return output;
}

/**
 * Generate footer for the webview, and add closing tags.
 */
export function getHtmlFooter() {
  return `</div>
</section>
</div>
</article>
</main>
</div>
</main>
</div>
</body>
</html>`;
}